sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t noybu1234/docker-react -f Dockerfile.dev .

scriprt:
  - docker run -e CI=true noybu1234/docker-react npm run test

